services:
#  playground:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
#    depends_on:
#      - postgres

  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123